[window]
opacity = 0.7
padding = { x = 11, y = 11 }

[font]
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Propo", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Propo", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Propo", style = "Bold Italic" }

size = 11.75

[cursor]
style = { shape = "Beam", blinking = "On" }
